name: pypi_publish

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  wheels:
    name: Wheels & SDist
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Build SDist and wheel
        run: pipx run build

      - uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: dist/*

      - name: Check metadata
        run: pipx run twine check dist/*

      - name: Install from wheel
        run: |
          pip install "$(find dist -name 'pdx2-*-py3-none-any.whl' -type f -print -quit)"[test]

      - name: Test wheel
        run: pytest

      - name: Install from sdist
        run: |
          pip uninstall pdx2 -y
          cp dist/pdx2-*.tar.gz pdx2.tar.gz
          pip install pdx2.tar.gz[test]

      - name: Test sdist
        run: pytest

  to_pypi:
    needs: [wheels]
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
